#!/usr/bin/env bash

# Split a git subtree into its own repository.
#
# Usage:
#   ./git-subtree-split-project <project_name> <project_path> <git_uri>
#   ./git-subtree-split-project promotions sites/all/modules/sparks/promotions git@git.example.com:promotions.git

if (( $# != 3 )); then
  echo "usage: $0 <project_name> <project_path> <git_uri>"
  exit 1
fi

project_name=$1
project_path=$2
git_uri=$3
project_branch="7.x-1.x"

echo "assuming i am in docroot and on a clean git of the branch you want to make this change in"
docroot=$(pwd)
main_branch=$(git rev-parse --abbrev-ref HEAD)
git status
git pull
git tag "BEFORE_SUBTREE_SPLIT_${project_name}"

echo "the subtree split may take a while (~1 min) due to large project history"

# Extract the subproject into a stand-alone branch containing only it.
git subtree split --prefix="$project_path" -b "$project_name"

echo "preparing a place to copy the new tree into. building the new folder and repo"
cd ..
mkdir "$project_name"
cd "$project_name"
git init
git remote add origin "$git_uri"
git checkout -b "$project_branch"

# Now have a local place to build the subproject.
# This transfers the contents of the temp branch from the master project
# into this new repo as the preferred branch.
git pull "$docroot" "$project_name:$project_branch"
git push origin "$project_branch"

echo "now replacing the subfolder in the master project with an included subtree"
cd "$docroot"
git remote add "$project_name" "$git_uri"
git rm -r "$project_path"
git commit -m "remove ${project_name} feature for splitting into sub-project" "$project_path"
git subtree add --prefix="$project_path" "$project_name" "$project_branch"
git tag "AFTER_SUBTREE_SPLIT_${project_name}"

# It's best to remove the reference to the sub-project remote immediately or else
# the subproject gets pulled into your project the next time you attempt a git pull.
# After hours of tracing, I can blame it on git rebase.
# http://stackoverflow.com/questions/27414132/git-subtree-split-merge-works-poorly/30204551#30204551
# So stop that.
git config branch.master.rebase false

echo "this process has already made the git commits to your project. check this now before pushing"
echo "you can revert to BEFORE_SUBTREE_SPLIT_${project_name} to back out now if there is a problem"
echo "running:"
echo "    git diff BEFORE_SUBTREE_SPLIT_${project_name} AFTER_SUBTREE_SPLIT_${project_name}"
echo "should show no changes at all"
echo "you can ignore these local tags, probably no need to push them"
