#!/usr/bin/env bash

# Extract a subdirectory from a git repository into a new stand-alone repo with history.
#
# Usage:
#   ./git-extract <repo_url> <folder_path> <new_project_name>
#   ./git-extract git@repo_site.com:/my_repo.git origin/folder/customlib/ customlib

if (( $# != 3 )); then
  echo "usage: $0 <repo_url> <folder_path> <new_project_name>"
  exit 1
fi

repo=$1
folder=$2
newproject=$3

git clone --no-hardlinks "$repo" "$newproject"

# The --no-hardlinks switch makes git use real file copies instead of hardlinking when
# cloning a local repository. The garbage collection and pruning actions will only work
# on blobs (file contents), not links. Then filter-branch and reset to exclude other
# files so they can be pruned.

cd "$newproject"
git filter-branch --subdirectory-filter "$folder" -- --all

# Delete the backup reflogs so the space can be truly reclaimed (although this makes
# the operation destructive).

git reset --hard
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now

# Remove the existing remote to avoid confusion.
git remote rm origin

# git remote add origin git@git.sparksinteractive.co.nz:kidshealth/$newproject.git

git config --add branch.6.x-1.x.remote origin
git config --add branch.6.x-1.x.merge refs/heads/6.x-1.x

# Commit to make the history work
git commit -m "removed all data but the folder that was extracted"

echo "done. remember to add a new remote origin, and commit and push the changes (especially including push --tags) to the destination branch"