#!/usr/bin/env bash

MEDIA_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="$(dirname $MEDIA_LIB_DIR)"
source "${MEDIA_LIB_DIR}/process_media.lib"

# process-dirname-as-keyword
# For all files given as arguments
# If we are in a subdirectory
# add the subdirname as a keyword tag

function processFile {
    local exif_option="-quiet -overwrite_original"
    local source_file="$1"
    if [[ ! -f "${source_file}" ]]; then
        echo "Error: $source_file is not a file"
        return 1
    fi
    local rp=$(realpath "$source_file")
    local dn=$(dirname "$rp")
    local subdir=$(basename "$dn")
    # exiftool wierdness to avoid duplicate tagging. Delete and set the tag.
    exiftool ${exif_option} "${source_file}" -XMP:Subject-="$subdir" -XMP:Subject+="$subdir"
    # exiftool ${exif_option} "${source_file}" -Keywords-="$subdir" -Keywords+="$subdir"
    # XMP:Subject works, and is what Bridge uses. Keywords does not seem to be a tag that is retained?
    echo "Added keyword from directory  '$subdir' to '$source_file'." >&2
    return 0
}

# Call the processFiles function with the provided arguments
parallelProcessFiles "$@"