#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/jellyfin-utils.lib"

# AddItemToCollection - Add item(s) to a Jellyfin collection
#
# Usage: AddItemToCollection COLLECTION_ID ITEM_ID [ITEM_ID ...]
#
# Examples:
#   AddItemToCollection "5f408f9d50b7ddd6da73b69228fbf3c6" "item-id-1"
#   AddItemToCollection "5f408f9d50b7ddd6da73b69228fbf3c6" "item-id-1" "item-id-2"

COLLECTION_ID="$1"
shift

jellyfin_require_args 2 $((1 + $#)) "Usage: $0 COLLECTION_ID ITEM_ID [ITEM_ID ...]" || exit 1
[ $# -gt 0 ] || { log_error "At least one ITEM_ID is required"; exit 1; }

ITEM_IDS=$(jellyfin_join_ids "," "$@")

log_info "Adding items to collection: $COLLECTION_ID"
log_debug "  Items: $ITEM_IDS"

jellyfin_request POST "/Collections/$COLLECTION_ID/Items?Ids=$ITEM_IDS"
jellyfin_handle_response "Items added to collection successfully"
