#!/usr/bin/env bash

# Items - Query Jellyfin items with flexible filtering
#
# Usage: Items [options]
#
# Options:
#   --type TYPE              Include item types (Video, Photo, PhotoAlbum, BoxSet)
#   --recursive              Search recursively (default: true)
#   --limit N                Limit results (default: 1000)
#   --fields FIELD1,FIELD2   Fields to include (default: basic fields)
#   --tags TAG               Filter by tag
#   --genres GENRE           Filter by genre
#   --parent-id ID           Filter by parent folder ID
#   --start-index N          Pagination start index
#   --help                   Show this help

INCLUDE_TYPES="Video,Photo"
RECURSIVE=true
LIMIT=1000
FIELDS="Path,Name,Id,Tags,Genres,Type"
EXTRA_PARAMS=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --type)
            INCLUDE_TYPES="$2"
            shift 2
            ;;
        --recursive)
            RECURSIVE=true
            shift
            ;;
        --no-recursive)
            RECURSIVE=false
            shift
            ;;
        --limit)
            LIMIT="$2"
            shift 2
            ;;
        --fields)
            FIELDS="$2"
            shift 2
            ;;
        --tags)
            EXTRA_PARAMS="${EXTRA_PARAMS}&Tags=$2"
            shift 2
            ;;
        --genres)
            EXTRA_PARAMS="${EXTRA_PARAMS}&Genres=$2"
            shift 2
            ;;
        --parent-id)
            EXTRA_PARAMS="${EXTRA_PARAMS}&ParentId=$2"
            shift 2
            ;;
        --start-index)
            EXTRA_PARAMS="${EXTRA_PARAMS}&StartIndex=$2"
            shift 2
            ;;
        --help)
            grep "^#" "$0" | grep -v "^#!/" | sed 's/^# //'
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Build URL
URL="http://$JELLYFIN_HOST:$JELLYFIN_PORT/Items?IncludeItemTypes=$INCLUDE_TYPES&Recursive=$RECURSIVE&Limit=$LIMIT&Fields=$FIELDS$EXTRA_PARAMS"

# Make request
curl -s -H "Authorization: MediaBrowser Token=\"$JELLYFIN_API_KEY\"" "$URL" | jq '.Items'
