#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/jellyfin-utils.lib"

eval curl -s $JELLYFIN_CURL_OPTIONS \
     "${JELLYFIN_API_URL}/System/Info" \
     | jq